# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ feature/** ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
    # - uses: actions/checkout@v4
    # - name: Build
    #  run: swift build -v
    # - name: Run tests
    #  run: swift test -v
