# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ feature/** ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Running the workflow!

      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install any dependencies
      # - name: Install Dependencies
      #  run: swift package resolve

      # Run tests on iPhone 15 Simulator with iOS 18.3
      - name: Run Tests on iPhone 15 Simulator (iOS 18.3)
        run: |
          xcodebuild test \
            -project FruitPicker/FruitPicker.xcodeproj \
            -scheme 'FruitPicker' \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.3'
            
